config/routes.rb
Rails.application.routes.draw do
  resources :strategies do
    get :personalized, on: :collection
  end
  resources :activities do 
    get :personalized, on: :collection
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations" }

   root 'welcome#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base

	belongs_to :user
end

app/models/strategy.rb
class Strategy < ActiveRecord::Base

	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 has_many :activities
 has_many :strategies
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  respond_to :json

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  def personalized
    @activities = current_user.activities if current_user
    render :index
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    puts params
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:content, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  before_filter :send_user_id

  private 

  def send_user_id
  	gon.user_id = current_user.id if current_user
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation)
	end

	def account_update_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
	end

end

app/controllers/strategies_controller.rb
class StrategiesController < ApplicationController
  before_action :set_strategy, only: [:show, :edit, :update, :destroy]
  respond_to :json

  # GET /strategies
  # GET /strategies.json
  def index
    @strategies = Strategy.all
  end

  # GET /strategies/1
  # GET /strategies/1.json
  def show
  end

  def personalized
    @strategies = current_user.strategies if current_user
    render :index
  end

  # GET /strategies/new
  def new
    @strategy = Strategy.new
  end

  # GET /strategies/1/edit
  def edit
  end

  # POST /strategies
  # POST /strategies.json
  def create
    puts params
    @strategy = Strategy.new(strategy_params)

    respond_to do |format|
      if @strategy.save
        format.html { redirect_to @strategy, notice: 'Strategy was successfully created.' }
        format.json { render :show, status: :created, location: @strategy }
      else
        format.html { render :new }
        format.json { render json: @strategy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /strategies/1
  # PATCH/PUT /strategies/1.json
  def update
    respond_to do |format|
      if @strategy.update(strategy_params)
        format.html { redirect_to @strategy, notice: 'Strategy was successfully updated.' }
        format.json { render :show, status: :ok, location: @strategy }
      else
        format.html { render :edit }
        format.json { render json: @strategy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /strategies/1
  # DELETE /strategies/1.json
  def destroy
    @strategy.destroy
    respond_to do |format|
      format.html { redirect_to strategies_url, notice: 'Strategy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_strategy
      @strategy = Strategy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def strategy_params
      params.require(:strategy).permit(:content, :user_id, :signal)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/strategies_helper.rb
module StrategiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Activities</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.content %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @activity.content %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/layouts/_footer.html.erb
<footer class="container-fluid text-center">
<!--   <a href="#myPage" title="To Top">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a> -->
  <!-- <p>Site made by Aleksander Cieślak</p>  -->
</footer>

app/views/layouts/_header.html.erb
<!-- <body>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">StocKING</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">Stocker</a></li> 
      <li><a href="#">Profile</a></li>

    </ul>
  </div>
</nav> -->

<nav class="navbar navbar-default navbar-fixed-top" id="myNavbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>

      <%= link_to "stocKING", :root, class:"navbar-brand", id:"logo" %>
        

    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
<!--         <li id="aboutTab"><a href="#about">ABOUT</a></li>
        <li id="servicesTab"><a href="#services">SERVICES</a></li> -->
        <% if current_user %>
          <li class="dropdown">
            <a onclick="myFunction()" class="dropbtn"><%= String(current_user.username.upcase+" ") %><span class="caret"></span></a>
            <ul id="myDropdown" class="dropdown-content">
                <% if current_user.admin == true %>
                  <li><%= link_to "ADMIN PANEL", '/admin', method: :get %></li>
                <% end %>
                <li><%= link_to "YOUR ACCOUNT", edit_user_registration_path, method: :get %></li>
                <li><%= link_to "LOG OUT" , destroy_user_session_path, method: :delete %></li>

            </ul>
          </li>
        <% else %>
          <li><%= link_to "LOG IN", new_user_session_path, method: :get %></li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>

    <!-- Theme Made By www.w3schools.com - No Copyright -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link href="http://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<!--     <link rel="stylesheet" href="css/jPages.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script src="js/jPages.js"></script>
     -->

    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
<!--     <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'> -->

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
  	<%= yield %>
  	<%= render 'layouts/footer' %>
  </body>
</html>

app/views/strategies/_form.html.erb
<%= form_for(@strategy) do |f| %>
  <% if @strategy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@strategy.errors.count, "error") %> prohibited this strategy from being saved:</h2>

      <ul>
      <% @strategy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/strategies/edit.html.erb
<h1>Editing Strategy</h1>

<%= render 'form' %>

<%= link_to 'Show', @strategy %> |
<%= link_to 'Back', strategies_path %>

app/views/strategies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Strategies</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @strategies.each do |strategy| %>
      <tr>
        <td><%= strategy.content %></td>
        <td><%= link_to 'Show', strategy %></td>
        <td><%= link_to 'Edit', edit_strategy_path(strategy) %></td>
        <td><%= link_to 'Destroy', strategy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Strategy', new_strategy_path %>

app/views/strategies/new.html.erb
<h1>New Strategy</h1>

<%= render 'form' %>

<%= link_to 'Back', strategies_path %>

app/views/strategies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @strategy.content %>
</p>

<%= link_to 'Edit', edit_strategy_path(@strategy) %> |
<%= link_to 'Back', strategies_path %>

app/views/welcome/_user_not_signed.html.erb
<div id="title" class="banner text-center">
  <h1>stocKING</h1> 
  <h2>Technical analysis web service</h2>
  <div class="title-content">
    Check your trading skills without any risk. This platform allows you to define your own strategies. You can test how they work on historical data. You can enable notifications and check what trading signals your strategies emitted. Our database contains every stock company from GPW! Sign up and get rich!
  </div>


</div>




<!-- <div id="about" class="container-fluid text-center ">
  <div class="row slideanim">
    <div class="col-sm-8">
      <h2>About Company Page</h2>
      <h4>Lorem ipsum..</h4> 
      <p>Lorem ipsum..</p>
      <button class="btn btn-default btn-lg">Get in Touch</button>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-signal logo"></span>
    </div>
  </div>
</div> -->

<!-- <div class="container-fluid bg-grey text-center">
  <div class="row slideanim">
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-globe logo"></span> 
    </div>
    <div class="col-sm-8">
      <h2>Our Values</h2>
      <h4><strong>MISSION:</strong> Our mission lorem ipsum..</h4> 
      <p><strong>VISION:</strong> Our vision Lorem ipsum..</p>
    </div>
  </div>
</div>
 -->

<!-- <div id="services" class="container-fluid text-center">
  <h2>SERVICES</h2>
  <h4>What we offer</h4>
  <br>
  <div class="row slideanim">
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-off logo-small"></span>
      <h4>POWER</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-heart logo-small"></span>
      <h4>LOVE</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-lock logo-small"></span>
      <h4>JOB DONE</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
    </div>
    <br><br>
  <div class="row slideanim">
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-leaf logo-small"></span>
      <h4>GREEN</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-certificate logo-small"></span>
      <h4>CERTIFIED</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-wrench logo-small"></span>
      <h4>HARD WORK</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
  </div>
</div>
 -->

<!-- <div class="container-fluid bg-grey text-center slideanim">
	<h2>What our customers say</h2>
	<div id="myCarousel" class="carousel slide text-center" data-ride="carousel">
	  
	  <ol class="carousel-indicators">
	    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
	    <li data-target="#myCarousel" data-slide-to="1"></li>
	    <li data-target="#myCarousel" data-slide-to="2"></li>
	  </ol>

	  
	  <div class="carousel-inner" role="listbox">
	    <div class="item active">
	    <h4>"This company is the best. I am so happy with the result!"<br><span style="font-style:normal;">Michael Roe, Vice President, Comment Box</span></h4>
	    </div>
	    <div class="item">
	      <h4>"One word... WOW!!"<br><span style="font-style:normal;">John Doe, Salesman, Rep Inc</span></h4>
	    </div>
	    <div class="item">
	      <h4>"Could I... BE any more happy with this company?"<br><span style="font-style:normal;">Chandler Bing, Actor, FriendsAlot</span></h4>
	    </div>
	  </div>

	
	  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
	    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	    <span class="sr-only">Previous</span>
	  </a>
	  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
	    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
	    <span class="sr-only">Next</span>
	  </a>
	</div>
</div>
 -->

app/views/welcome/_user_signed.html.erb
<div id="services" class="mainmenu-bar text-center">

  <%= include_gon %>

  <div id="wizard_section_button" class="section-wrapper" index=0>
    <span class="glyphicon glyphicon-usd logo-small"></span>
    <h4>WIZARD</h4>
    <div class="p-wrapper">
      <p>Define your strategies and calculations</p>
    </div>
  </div>

  <div id="strategies_section_button" class="section-wrapper" index=1> 
    <span class="glyphicon glyphicon-tower logo-small"></span>
    <h4>STRATEGIES</h4>
    <div class="p-wrapper">
      <p>Check your strategies</p>
    </div>
  </div>


  <div id="activity_section_button" class="section-wrapper" index=2> 
    <span class="glyphicon glyphicon-signal logo-small"></span>
    <h4>CALCULATIONS LOG</h4>
    <div class="p-wrapper">
      <p>Check your results</p>
    </div>
  </div>

</div>

<div class="main-content">

  <div id="companies_section companies" class="container-primary" > 
    <div>

        <div class="general-list">
          <ul>
            <li id="choose_company_button">1. Choose company</li>
            <li id="choose_indicator_button">2. Choose indicator</li>
            <li id="add_parameters_button">3. Add parameters</li>
            <li id="results_button">4. Check your results</li>
          </ul>
        </div>  

        <div class="user-content companies" id="companies_chooser">

            <div class="detailed-info text-center" style="position:relative">
              <!-- <button id="companies_fold_button">Fold</button> -->
              <h2>Stock companies</h2>
            </div>

            <div id="companies_container" class="content-list">
            </div>

            <div id="companies_paginator" class="content-list">
            </div>

            <div id="company_info" class="detailed-info text-center">
            </div>

        </div>

        <div class="user-content" id="indicators_chooser">

         <div class="detailed-info text-center">
           <h2>Indicators</h2>
         </div>

         <div id="indicators_container" class="content-list">
         </div>

         <div id="indicators_paginator" class="content-list">
         </div>

        </div>

        <div class="user-content" id="parameters_chooser">

         <div class="detailed-info text-center">
          <h2>Parameters</h2>
         </div>
          
         <div id="indicator_info" class="detailed-info text-center">
          Choose your indicator first!
         </div>

        </div>

        <div class="user-content" id="results_viewer">
          <div id="result_info" class="detailed-info text-center">
          </div>
        </div>

    </div>
  </div>

  <div id="strategies_section" class="container-primary"> 
    <div>
      <div id="strategy_container" class="activity-info"> 
      </div>
    </div>
  </div>


  <div id="activity_section" class="container-primary"> 
    <div>
      <div id="activity_container" class="activity-info"> 
      </div>
    </div>
  </div>

</div> 

app/views/welcome/index.html.erb
<% if current_user %>
  <%= render 'welcome/user_signed' %>
<% else %>
  <%= render 'welcome/user_not_signed' %>
<% end %>  